/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32l476xx.h"
#include "stm32l476xx_gpio_Driver.h"
#include "stm32l476_systick_Driver.h"


void SysTick_DelayMs(uint32_t ms)
{
    for(uint32_t i = 0; i < ms; i++)
    {
        /* Load value for 1ms */

        SYSTICK->LOAD = 4000 - 1;

        /* Clear current value */

        SYSTICK->VAL = 0;

        /* Enable SysTick
         *
         * Bit0 = ENABLE
         * Bit2 = CLKSOURCE (processor clock)
         */

        SYSTICK->CTRL = (1 << 0) | (1 << 2);

        /* Wait until COUNTFLAG becomes 1 */

        while(!(SYSTICK->CTRL & (1 << 16)));

        /* Stop timer */

        SYSTICK->CTRL &= ~(1 << 0);
    }
}

int main(void)
{
    GPIO_peripherial_Clk_Cntrl(GPIOA,ENABLE);

    GPIO_config();

    while(1)
    {
        GPIO_Toggle_Pin(GPIOA,5);

        SysTick_DelayMs(1000);
    }

}


