/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32l476xx.h"
#include "stm32l476xx_gpio_Driver.h"
#include "stm32l476xx_uart_Driver.h"


extern UART_Handle_t UART4Handle;


uint8_t TxData[] = "HELLO";
uint8_t RxData[6];



int main(void)
{
	GPIO_peripherial_Clk_Cntrl(GPIOA,SET);
	UART4_PCLK_EN();

	UART_GPIO_Init();

	UART_Config();

	UART_IRQInterruptConfig(IRQ_NO_UART4,ENABLE);

	UART_IRQPriorityConfig(IRQ_NO_UART4,2);


//	for(int i = 0; i < 5; i++)
//	{
//	    UART_SendData(UART4,&TxData[i],1);
//
//	    UART_ReceiveData(UART4,&RxData[i],1);
//	}

	UART_SendDataIT(&UART4Handle,TxData,5);

	UART_ReceiveDataIT(&UART4Handle,RxData,5);

}



void UART4_IRQHandler(void)
{
    UART_IRQHandling(&UART4Handle);
}

//void EXTI15_10_IRQHandler(void)
//{
//    GPIO_IRQHandling(13);
//}
