/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//#include "core_cm4.h"   // for Cortex-M4
#include <stdio.h>
#include <stdint.h>
#include "string.h"
#include "stm32l476xx.h"
#include "stm32l476xx_gpio_Driver.h"
#include "stm32l476x_spi_Driver.h"
#include "stm32l476xx_tim_driver.h"
#include "stm32l476_systick_Driver.h"

#include "w25qxx.h"


#define SCB_CPACR   (*(volatile uint32_t*)0xE000ED88)
#define FPU_FPCCR   (*(volatile uint32_t*)0xE000EF34)
#define MAX_LOGS           1024
#define LOG_SIZE           4
#define OBJECT_THRESHOLD   20.0f
#define OBJECT_ENTER 1
#define OBJECT_EXIT  2

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern SPI_Handle_t SPI1Handle;

uint8_t Spi_Tx_Buff[2];
uint8_t Spi_Rx_Buff[4];

static uint32_t rising_time = 0;
static uint32_t falling_time = 0;
static uint8_t capture_state = 0;
static float distance_cm = 0;
uint8_t measurement_done =0;

volatile uint8_t Exti_Flag = 0;

uint8_t Write_Buf[4];
uint8_t Read_Buf[4];

float Retrived_Frm_Flash;

uint32_t cfgr=0;

uint32_t testVal = 0x12345678;


uint8_t tx[4] = {0x11, 0x22, 0x33, 0x44};
uint8_t rx[4];
uint32_t ft = 12;
uint32_t r_ft;
uint32_t flash_id;

typedef struct
{
    uint8_t event;
    float distance;
    uint32_t timestamp;
}ObjectLog_t;


ObjectLog_t logData;

uint32_t address = 0;

uint32_t logCounter = 0;

uint8_t object_present = 0;

uint32_t system_time = 0;


void SysTick_DelayMs(uint32_t ms)
{
    for(uint32_t i = 0; i < ms; i++)
    {
        /* Load value for 1ms */

        SYSTICK->LOAD = 4000 - 1;

        /* Clear current value */

        SYSTICK->VAL = 0;

        /* Enable SysTick
         *
         * Bit0 = ENABLE
         * Bit2 = CLKSOURCE (processor clock)
         */

        SYSTICK->CTRL = (1 << 0) | (1 << 2);

        /* Wait until COUNTFLAG becomes 1 */

        while(!(SYSTICK->CTRL & (1 << 16)));

        /* Stop timer */

        SYSTICK->CTRL &= ~(1 << 0);
    }
}



void delay_us(uint32_t time) {
	for (uint32_t i = 0; i < time * 10; i++)
		;
}

void delay_ms(uint32_t time) {
	for (uint32_t i = 0; i < time * 8000; i++)
		__asm("nop");
}




void Store_Log(uint8_t event,float distance)
{
    ObjectLog_t log;

    log.event = event;

    log.distance = distance;

    log.timestamp = system_time;

    /* Erase sector when new sector starts */
    if((address % 4096) == 0)
    {
        w25q_erase_sector(address / 4096);

        while(w25q_read_status() & 0x01);
    }

    /* Write structure */
    w25q_write(address,
               (uint8_t*)&log,
               sizeof(ObjectLog_t));

    while(w25q_read_status() & 0x01);

    address += sizeof(ObjectLog_t);

    logCounter++;

    /* Circular logging */
    if(logCounter >= MAX_LOGS)
    {
        logCounter = 0;
        address = 0;
    }
}


void Read_All_Logs(void)
{
    ObjectLog_t readLog;

    printf("\r\n========= FLASH LOGS =========\r\n");

    uint32_t count;

    if(logCounter < MAX_LOGS)
        count = logCounter;
    else
        count = MAX_LOGS;

    for(uint32_t i = 0; i < count; i++)
    {
        uint32_t read_address;

        read_address = i * sizeof(ObjectLog_t);

        w25q_read(read_address,
                  (uint8_t*)&readLog,
                  sizeof(ObjectLog_t));

        printf("Log %ld\r\n",i);

        if(readLog.event == OBJECT_ENTER)
        {
            printf("EVENT    : OBJECT ENTER\r\n");
        }
        else if(readLog.event == OBJECT_EXIT)
        {
            printf("EVENT    : OBJECT EXIT\r\n");
        }

        printf("DISTANCE : %.2f cm\r\n",
               readLog.distance);

        printf("TIME     : %ld\r\n",
               readLog.timestamp);

        printf("-----------------------------\r\n");
    }
}

void Ultrasonic_Trigger(void)
{
    GPIO_Write_Output_Pin(GPIOA, 0, DISABLE);
	delay_us(2);
    GPIO_Write_Output_Pin(GPIOA, 0, ENABLE);
    delay_us(10);
    GPIO_Write_Output_Pin(GPIOA, 0, DISABLE);
}




int main(void)
{
	// Enable CP10 and CP11 full access
		SCB_CPACR |= (0xF << 20);
	// Disable lazy stacking
	    FPU_FPCCR &= ~((1 << 31) | (1 << 30)); // ASPEN=bit31, LSPEN=bit30


	    GPIO_peripherial_Clk_Cntrl(GPIOA,SET);
		GPIO_peripherial_Clk_Cntrl(GPIOC,SET);

	    TIM1_PCLK_EN();
	    TIM2_PCLK_EN();
		SPI_PCLK_EN(SPI1,SET);
		SPI_PeripheralControl(SPI1,ENABLE);
	    GPIO_Config();
		Button_Gpio_Config();
	    Tim1_GPIO_Config();
		SPI1_GPIO_Config();

		SPI_Config();
		SPI_PeripheralControl(SPI1,ENABLE);


	    TIM_Handle_t htim1;
	    TIM2345_Handle_t htim2;


	    htim1.pTIMx = TIM1;

	    htim1.TIM_Config.Prescaler = 3;
	    htim1.TIM_Config.Period = 0xFFFF;   // better for capture test
	    htim1.TIM_Config.ICPolarity = TIM_IC_RISING_EDGE;
	    htim1.TIM_Config.ICSelection = TIM_ICSELECTION_DIRECTTI;

	    htim2.pTIMx = TIM2;
	    htim2.TIM2345_Config.Prescaler = 3;
	    htim2.TIM2345_Config.Period = 0xFFFFFFFF;

	    TIM_Init(&htim1);
	    TIM_IC_Init(&htim1);
	    TIM_Start(TIM1);
	    TIM2345_Init(&htim2);
	    TIM2345_Start(TIM2);

	    TIM2->CR1 |= (0x01<<0);

	    TIM1->DIER |= (1 << 1);


		GPIO_IRQInterruptConfig(IRQ_NO_EXTI15_10, ENABLE);

		GPIO_IRQPriorityConfig(IRQ_NO_EXTI15_10, 1);

	    Timer_IRQInterruptConfig(TIM1_CC_IRQn, ENABLE);

	    Timer_IRQPriorityConfig(TIM1_CC_IRQn, 0);


	    w25q_reset();

	    flash_id = w25q_readID();
//
//	    while(w25q_read_status() & 0x01);
//
//	    w25q_write(0x000000, (uint8_t*)&ft, 4);
//
//	    while(w25q_read_status() & 0x01);
//
//	    w25q_read(0x000000, (uint8_t*)&r_ft, 4);



        // Loop forever
	    while(1)
	    {
	        system_time++;

	        measurement_done = 0;

	        Ultrasonic_Trigger();

	        uint32_t timeout = 500000;

	        while((measurement_done == 0) && timeout--);

	        float distance = distance_cm;

//	        printf("Distance : %.2f cm\r\n",distance);

	        /****************************************
	         * OBJECT ENTER DETECTION
	         ****************************************/
	        if((distance < OBJECT_THRESHOLD) &&
	           (object_present == 0))
	        {
	            object_present = 1;

	            printf("OBJECT ENTERED\r\n");

	            Store_Log(OBJECT_ENTER,
	                      distance);
	        }

	        /****************************************
	         * OBJECT EXIT DETECTION
	         ****************************************/
	        else if((distance > OBJECT_THRESHOLD) &&
	                (object_present == 1))
	        {
	            object_present = 0;

	            printf("OBJECT EXITED\r\n");

	            Store_Log(OBJECT_EXIT,
	                      distance);
	        }

	        /****************************************
	         * BUTTON PRESSED
	         ****************************************/
	        if(Exti_Flag)
	        {
	            delay_ms(200);

	            Exti_Flag = 0;

	            Read_All_Logs();
	        }

	        delay_ms(100);
	    }


}



void TIM1_CC_IRQHandler(void)
{
    if(TIM1->SR & (1 << 1))
    {
        uint32_t capture = TIM1->CCR1;

        TIM1->SR &= ~(1 << 1);

        if(capture_state == 0)
        {
            rising_time = capture;

            TIM1->CCER |= (1 << 1);

            capture_state = 1;
        }
        else
        {
            falling_time = capture;
            uint32_t pulse;

            if(falling_time >= rising_time)
            {
                pulse = falling_time - rising_time;
            }
            else
            {
                pulse = (0xFFFF - rising_time + 1) + falling_time;
            }

//            distance_cm = pulse * 100 / 5800;

            distance_cm = pulse /58.0;

            capture_state = 0;

            TIM1->CCER &= ~(1 << 1);

            measurement_done = 1;
        }
    }
}



void EXTI15_10_IRQHandler(void)
{
    GPIO_IRQHandling(13);

    Exti_Flag = 1;

//    EXTI->EXTI_IMR1 &= ~(1 << 13);
}


