/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32l476xx.h"
#include "stm32l476xx_gpio_Driver.h"
#include "stm32l476x_spi_Driver.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern SPI_Handle_t SPI1Handle;

uint8_t Spi_Tx_Buff[2];
uint8_t Spi_Rx_Buff[2];



int main(void)
{

	GPIO_peripherial_Clk_Cntrl(GPIOC,SET);
	GPIO_peripherial_Clk_Cntrl(GPIOA,SET);
	SPI_PCLK_EN(SPI1,SET);
	SPI1_GPIO_Config();
	SPI_Config();
	SPI_PeripheralControl(SPI1,ENABLE);
	SPI_IRQInterruptConfig(IRQ_NO_SPI1, ENABLE);
	SPI_IRQPriorityConfig(IRQ_NO_SPI1,2);
	 Spi_Tx_Buff[0] = 0x55;
	 Spi_Tx_Buff[1] = 0xAA;


//	SPI_SendData(SPI1, Spi_Tx_Buff, 4);

//	SPI_ReceiveData(SPI1, Spi_Rx_Buff, 2);

//	 SPI_SendReceiveData(SPI1,Spi_Tx_Buff,Spi_Rx_Buff,2);

	 SPI_SendDataIT(&SPI1Handle,Spi_Tx_Buff,2);

	 SPI_ReceiveDataIT(&SPI1Handle,Spi_Rx_Buff,2);

}




void SPI1_IRQHandler(void)
{
    SPI_IRQHandling(&SPI1Handle);
}


