/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//#include "core_cm4.h"   // for Cortex-M4
#include <stdio.h>
#include <stdint.h>
#include "string.h"
#include "stm32l476xx.h"
#include "stm32l476xx_gpio_Driver.h"
#include "stm32l476x_spi_Driver.h"
#include "stm32l476xx_tim_driver.h"
#include "stm32l476_systick_Driver.h"

#include "w25qxx.h"


#define SCB_CPACR   (*(volatile uint32_t*)0xE000ED88)
#define FPU_FPCCR   (*(volatile uint32_t*)0xE000EF34)
#define MAX_LOGS           1024
#define LOG_SIZE           4
#define OBJECT_THRESHOLD   20.0f
#define OBJECT_ENTER 1
#define OBJECT_EXIT  2

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern SPI_Handle_t SPI1Handle;

uint8_t Spi_Tx_Buff[2];
uint8_t Spi_Rx_Buff[4];

static uint32_t rising_time = 0;
static uint32_t falling_time = 0;
static uint8_t capture_state = 0;
static float distance_cm = 0;
uint8_t measurement_done =0;

volatile uint8_t Exti_Flag = 0;

uint8_t Write_Buf[4];
uint8_t Read_Buf[4];

float Retrived_Frm_Flash;

uint32_t cfgr=0;

uint32_t testVal = 0x12345678;


uint8_t tx[4] = {0x11, 0x22, 0x33, 0x44};
uint8_t rx[4];
uint32_t ft = 12;
uint32_t r_ft;
uint32_t flash_id;

typedef struct
{
    uint8_t event;
    float distance;
    uint32_t timestamp;
}ObjectLog_t;


ObjectLog_t logData;

uint32_t address = 0;

uint32_t logCounter = 0;

uint8_t object_present = 0;

uint32_t system_time = 0;

//uint32_t count =0;
//uint32_t check =0;
//int main(void)
//{

//	GPIO_peripherial_Clk_Cntrl(GPIOA,SET);
//	SPI_PCLK_EN(SPI1,SET);
//	SPI1_GPIO_Config();
//	SPI_Config();
//	SPI_IRQInterruptConfig(IRQ_NO_SPI1, ENABLE);
//	SPI_IRQPriorityConfig(IRQ_NO_SPI1,2);
//	 Spi_Tx_Buff[0] = 0x55;
//	 Spi_Tx_Buff[1] = 0xAA;


//	SPI_SendData(SPI1, Spi_Tx_Buff, 4);

//	SPI_ReceiveData(SPI1, Spi_Rx_Buff, 2);

//	 SPI_SendReceiveData(SPI1,Spi_Tx_Buff,Spi_Rx_Buff,2);
//
//	 SPI_SendDataIT(&SPI1Handle,Spi_Tx_Buff,2);
//
//	 SPI_ReceiveDataIT(&SPI1Handle,Spi_Rx_Buff,2);


//}

void SysTick_DelayMs(uint32_t ms)
{
    for(uint32_t i = 0; i < ms; i++)
    {
        /* Load value for 1ms */

        SYSTICK->LOAD = 4000 - 1;

        /* Clear current value */

        SYSTICK->VAL = 0;

        /* Enable SysTick
         *
         * Bit0 = ENABLE
         * Bit2 = CLKSOURCE (processor clock)
         */

        SYSTICK->CTRL = (1 << 0) | (1 << 2);

        /* Wait until COUNTFLAG becomes 1 */

        while(!(SYSTICK->CTRL & (1 << 16)));

        /* Stop timer */

        SYSTICK->CTRL &= ~(1 << 0);
    }
}

//void delay_us(uint32_t us)
//{
//    TIM2->CNT = 0;              // reset counter
//
//    while(TIM2->CNT < us);
//
//}

void delay_us(uint32_t time) {
	for (uint32_t i = 0; i < time * 10; i++)
		;
}

void delay_ms(uint32_t time) {
	for (uint32_t i = 0; i < time * 8000; i++)
		__asm("nop");
}




void Store_Log(uint8_t event,float distance)
{
    ObjectLog_t log;

    log.event = event;

    log.distance = distance;

    log.timestamp = system_time;

    /* Erase sector when new sector starts */
    if((address % 4096) == 0)
    {
        w25q_erase_sector(address / 4096);

        while(w25q_read_status() & 0x01);
    }

    /* Write structure */
    w25q_write(address,
               (uint8_t*)&log,
               sizeof(ObjectLog_t));

    while(w25q_read_status() & 0x01);

    address += sizeof(ObjectLog_t);

    logCounter++;

    /* Circular logging */
    if(logCounter >= MAX_LOGS)
    {
        logCounter = 0;
        address = 0;
    }
}


void Read_All_Logs(void)
{
    ObjectLog_t readLog;

    printf("\r\n========= FLASH LOGS =========\r\n");

    uint32_t count;

    if(logCounter < MAX_LOGS)
        count = logCounter;
    else
        count = MAX_LOGS;

    for(uint32_t i = 0; i < count; i++)
    {
        uint32_t read_address;

        read_address = i * sizeof(ObjectLog_t);

        w25q_read(read_address,
                  (uint8_t*)&readLog,
                  sizeof(ObjectLog_t));

        printf("Log %ld\r\n",i);

        if(readLog.event == OBJECT_ENTER)
        {
            printf("EVENT    : OBJECT ENTER\r\n");
        }
        else if(readLog.event == OBJECT_EXIT)
        {
            printf("EVENT    : OBJECT EXIT\r\n");
        }

        printf("DISTANCE : %.2f cm\r\n",
               readLog.distance);

        printf("TIME     : %ld\r\n",
               readLog.timestamp);

        printf("-----------------------------\r\n");
    }
}
//void delay_us(uint32_t us)
//{
//    uint32_t start = TIM2->CNT;
//    while ((TIM2->CNT - start) < us)
//    	{
//    	count++;
//    	}
//}


//float Ultrasonic_ReadDistance()
//{
//	 uint32_t timeout = 30000;
//	uint32_t pulse_width = 0;
//	capture_state = 0;
//
//	GPIO_Write_Output_Pin(GPIOA,0,ENABLE);
//	delay_us(10);
//	GPIO_Write_Output_Pin(GPIOA,0,DISABLE);
//
//
//	while(timeout--)
//	{
//	    if(TIM1->SR & (1 << 1))
//	    {
//	        TIM1->SR &= ~(1 << 1);
//
//	        if(capture_state == 0)
//	        {
//	            rising_time = TIM1->CCR1;
//	            TIM1->CCER |= (1 << 1); // falling edge
//	            capture_state = 1;
//	        }
//	        else
//	        {
//	            falling_time = TIM1->CCR1;
//
//	            if(falling_time > rising_time)
//	                pulse_width = falling_time - rising_time;
//	            else
//	                pulse_width = (0xFFFF - rising_time) + falling_time;
//
//	            TIM1->CCER &= ~(1 << 1);
//
//	            break;   // IMPORTANT
//	        }
//	    }
//	}
//
//	distance_cm = pulse_width / 58.0f;
//	return distance_cm;
//}
void Ultrasonic_Trigger(void)
{
    GPIO_Write_Output_Pin(GPIOA, 0, DISABLE);
	delay_us(2);
    GPIO_Write_Output_Pin(GPIOA, 0, ENABLE);
    delay_us(10);
    GPIO_Write_Output_Pin(GPIOA, 0, DISABLE);
}

/*int main(void)
{

	cfgr = RCC->CFGR;
	// Enable CP10 and CP11 full access
	SCB_CPACR |= (0xF << 20);

	// Disable lazy stacking
	FPU_FPCCR &= ~((1 << 31) | (1 << 30)); // ASPEN=bit31, LSPEN=bit30





    GPIO_peripherial_Clk_Cntrl(GPIOA,SET);
	GPIO_peripherial_Clk_Cntrl(GPIOC,SET);

    TIM1_PCLK_EN();
    TIM2_PCLK_EN();
	SPI_PCLK_EN(SPI1,SET);
	SPI_PeripheralControl(SPI1,ENABLE);
    GPIO_Config();
	Button_Gpio_Config();
    Tim1_GPIO_Config();
	SPI1_GPIO_Config();

	SPI_Config();
	SPI_PeripheralControl(SPI1,ENABLE);


    TIM_Handle_t htim1;
    TIM2345_Handle_t htim2;


    htim1.pTIMx = TIM1;

    htim1.TIM_Config.Prescaler = 3;
    htim1.TIM_Config.Period = 0xFFFF;   // better for capture test
    htim1.TIM_Config.ICPolarity = TIM_IC_RISING_EDGE;
    htim1.TIM_Config.ICSelection = TIM_ICSELECTION_DIRECTTI;

    htim2.pTIMx = TIM2;
    htim2.TIM2345_Config.Prescaler = 3;
    htim2.TIM2345_Config.Period = 0xFFFF;

    TIM_Init(&htim1);
    TIM_IC_Init(&htim1);
    TIM_Start(TIM1);
    TIM2345_Init(&htim2);
    TIM2345_Start(TIM2);

    TIM1->DIER |= (1 << 1);

	W25Q_Init();

	W25Q_EraseSector(0);

	GPIO_IRQInterruptConfig(IRQ_NO_EXTI15_10, ENABLE);

	GPIO_IRQPriorityConfig(IRQ_NO_EXTI15_10, 1);

    Timer_IRQInterruptConfig(TIM1_CC_IRQn, ENABLE);

    Timer_IRQPriorityConfig(TIM1_CC_IRQn, 0);




//    while(1)
//    {
//        // wait for capture event
//        while(!(TIM1->SR & (1 << 1)));
//
//        // read captured value
//        count = TIM1->CCR1;
//
//        // clear flag
//        TIM1->SR &= ~(1 << 1);
//    }

//    while(1)
//    {
//    	float distance = Ultrasonic_ReadDistance();
//    }


	uint32_t address = 0;

    while(1)
    {
        measurement_done = 0;

        Ultrasonic_Trigger();

        // wait for ISR to complete
        while(measurement_done == 0);


//        float d = distance_cm;
//
//
//		memcpy(Write_Buf, &d, 4);
//
//		W25Q_Write(address, Write_Buf, 4);
//
//		logCounter++;
//
//		SysTick_DelayMs(10);
//
//		W25Q_Read(address, Read_Buf, 4);
//
//		if (Exti_Flag) {
//			Exti_Flag = 0;
//
//			uint32_t count = (logCounter < MAX_LOGS) ? logCounter : MAX_LOGS;
//
//			for (uint32_t i = 0; i < count; i++)
//			{
//				uint32_t index = (logCounter - count + i) % MAX_LOGS;
//				uint32_t read_addr = index * LOG_SIZE;
//
//				W25Q_Read(read_addr, Read_Buf, 4);
//
//				memcpy(&Retrived_Frm_Flash, Read_Buf, 4);
//
//				printf("[%ld] Distance = %.2f\r\n", (logCounter - i),Retrived_Frm_Flash);
//			}
//		}
//
//		address += 4;
//
//		if (address >= (MAX_LOGS * LOG_SIZE))
//			address = 0;
//
//		SysTick_DelayMs(100);

        float d = distance_cm;
        memcpy(Write_Buf, &d, sizeof(float));

        // 1. Enable write
        W25Q_WriteEnable();

        // 2. Erase sector if first time writing here
        if ((address % W25Q_SECTOR_SIZE) == 0) {
            W25Q_EraseSector(address);
            while (W25Q_ReadStatus1() & 0x01); // wait until erase completes
        }

        // 3. Program data
        W25Q_Write(address, Write_Buf, sizeof(float));

        // 4. Poll until WIP clears
        while (W25Q_ReadStatus1() & 0x01);

        // 5. Read back
        W25Q_Read(address, Read_Buf, sizeof(float));

        float Retrived_Frm_Flash;
        memcpy(&Retrived_Frm_Flash, Read_Buf, sizeof(float));

        // 6. Verify
        if (memcmp(Write_Buf, Read_Buf, sizeof(float)) == 0) {
            printf("Flash write OK: %.2f\r\n", Retrived_Frm_Flash);
        } else {
            printf("Flash write FAILED\r\n");
        }

        address += 4;
        if (address >= (MAX_LOGS * LOG_SIZE))
            address = 0;
    }

}*/


int main(void)
{
	// Enable CP10 and CP11 full access
		SCB_CPACR |= (0xF << 20);
	// Disable lazy stacking
	    FPU_FPCCR &= ~((1 << 31) | (1 << 30)); // ASPEN=bit31, LSPEN=bit30


	    GPIO_peripherial_Clk_Cntrl(GPIOA,SET);
		GPIO_peripherial_Clk_Cntrl(GPIOC,SET);

	    TIM1_PCLK_EN();
	    TIM2_PCLK_EN();
		SPI_PCLK_EN(SPI1,SET);
		SPI_PeripheralControl(SPI1,ENABLE);
	    GPIO_Config();
		Button_Gpio_Config();
	    Tim1_GPIO_Config();
		SPI1_GPIO_Config();

		SPI_Config();
		SPI_PeripheralControl(SPI1,ENABLE);


	    TIM_Handle_t htim1;
	    TIM2345_Handle_t htim2;


	    htim1.pTIMx = TIM1;

	    htim1.TIM_Config.Prescaler = 3;
	    htim1.TIM_Config.Period = 0xFFFF;   // better for capture test
	    htim1.TIM_Config.ICPolarity = TIM_IC_RISING_EDGE;
	    htim1.TIM_Config.ICSelection = TIM_ICSELECTION_DIRECTTI;

	    htim2.pTIMx = TIM2;
	    htim2.TIM2345_Config.Prescaler = 3;
	    htim2.TIM2345_Config.Period = 0xFFFFFFFF;

	    TIM_Init(&htim1);
	    TIM_IC_Init(&htim1);
	    TIM_Start(TIM1);
	    TIM2345_Init(&htim2);
	    TIM2345_Start(TIM2);

	    TIM2->CR1 |= (0x01<<0);

	    TIM1->DIER |= (1 << 1);


		GPIO_IRQInterruptConfig(IRQ_NO_EXTI15_10, ENABLE);

		GPIO_IRQPriorityConfig(IRQ_NO_EXTI15_10, 1);

	    Timer_IRQInterruptConfig(TIM1_CC_IRQn, ENABLE);

	    Timer_IRQPriorityConfig(TIM1_CC_IRQn, 0);


	    w25q_reset();

	    flash_id = w25q_readID();
//
//	    while(w25q_read_status() & 0x01);
//
//	    w25q_write(0x000000, (uint8_t*)&ft, 4);
//
//	    while(w25q_read_status() & 0x01);
//
//	    w25q_read(0x000000, (uint8_t*)&r_ft, 4);



        // Loop forever
	    while(1)
	    {
	        system_time++;

	        measurement_done = 0;

	        Ultrasonic_Trigger();

	        uint32_t timeout = 500000;

	        while((measurement_done == 0) && timeout--);

	        float distance = distance_cm;

//	        printf("Distance : %.2f cm\r\n",distance);

	        /****************************************
	         * OBJECT ENTER DETECTION
	         ****************************************/
	        if((distance < OBJECT_THRESHOLD) &&
	           (object_present == 0))
	        {
	            object_present = 1;

	            printf("OBJECT ENTERED\r\n");

	            Store_Log(OBJECT_ENTER,
	                      distance);
	        }

	        /****************************************
	         * OBJECT EXIT DETECTION
	         ****************************************/
	        else if((distance > OBJECT_THRESHOLD) &&
	                (object_present == 1))
	        {
	            object_present = 0;

	            printf("OBJECT EXITED\r\n");

	            Store_Log(OBJECT_EXIT,
	                      distance);
	        }

	        /****************************************
	         * BUTTON PRESSED
	         ****************************************/
	        if(Exti_Flag)
	        {
	            delay_ms(200);

	            Exti_Flag = 0;

	            Read_All_Logs();
	        }

	        delay_ms(100);
	    }


}


//void TIM1_CC_IRQHandler(void)
//{
//    if(TIM1->SR & (1 << 1))   // CC1IF
//    {
//        TIM1->SR &= ~(1 << 1); // clear flag
//
//        if(capture_state == 0)
//        {
//            // Rising edge
//            rising_time = TIM1->CCR1;
//
//            // switch to falling edge
//            TIM1->CCER |= (1 << 1);
//            capture_state = 1;
//        }
//        else
//        {
//            // Falling edge
//            falling_time = TIM1->CCR1;
//
//            uint32_t pulse;
//
//            if(falling_time >= rising_time)
//                pulse = falling_time - rising_time;
//            else
//                pulse = (0xFFFF - rising_time) + falling_time;
//
//            distance_cm = pulse / 58.0f;
//
//            capture_state = 0;
//
//            TIM1->CCER &= ~(1 << 1);
//
//            measurement_done = 1;
//        }
//    }
//}

void TIM1_CC_IRQHandler(void)
{
    if(TIM1->SR & (1 << 1))
    {
        uint32_t capture = TIM1->CCR1;

        TIM1->SR &= ~(1 << 1);

        if(capture_state == 0)
        {
            rising_time = capture;

            TIM1->CCER |= (1 << 1);

            capture_state = 1;
        }
        else
        {
            falling_time = capture;
            uint32_t pulse;

            if(falling_time >= rising_time)
            {
                pulse = falling_time - rising_time;
            }
            else
            {
                pulse = (0xFFFF - rising_time + 1) + falling_time;
            }

//            distance_cm = pulse * 100 / 5800;

            distance_cm = pulse /58.0;

            capture_state = 0;

            TIM1->CCER &= ~(1 << 1);

            measurement_done = 1;
        }
    }
}

//void SPI1_IRQHandler(void)
//{
//    SPI_IRQHandling(&SPI1Handle);
//}

void EXTI15_10_IRQHandler(void)
{
    GPIO_IRQHandling(13);

    Exti_Flag = 1;

//    EXTI->EXTI_IMR1 &= ~(1 << 13);
}


